"""ORM 模型统一出口。"""
from app.models.advanced import (
    StkCheck,
    StkCheckItem,
    StkOtherIo,
    StkOtherIoItem,
    StkTransfer,
    StkTransferItem,
)
from app.models.base import (
    BaseCategory,
    BaseLocation,
    BaseProduct,
    BaseProductUnit,
    BaseShelf,
    BaseSupplier,
    BaseUnit,
    BaseWarehouse,
)
from app.models.ocr import (
    AiSuggestion,
    OcrRecord,
)
from app.models.requisition import (
    OutRequisition,
    OutRequisitionItem,
)
from app.models.stock import (
    PchPurchaseIn,
    PchPurchaseInItem,
    StkOpening,
    StkOpeningItem,
    StkStock,
    StkStockLog,
)
from app.models.sys import (
    SysBackupLog,
    SysConfig,
    SysFile,
    SysModule,
    SysModuleMigration,
    SysNotification,
    SysNotificationDelivery,
    SysOperationLog,
    SysPermission,
    SysRole,
    SysRolePermission,
    SysSession,
    SysStorage,
    SysUser,
)

__all__ = [
    "BaseCategory",
    "BaseLocation",
    "BaseProduct",
    "BaseProductUnit",
    "BaseShelf",
    "BaseSupplier",
    "BaseUnit",
    "BaseWarehouse",
    "AiSuggestion",
    "OcrRecord",
    "StkCheck",
    "StkCheckItem",
    "StkOtherIo",
    "StkOtherIoItem",
    "StkTransfer",
    "StkTransferItem",
    "OutRequisition",
    "OutRequisitionItem",
    "PchPurchaseIn",
    "PchPurchaseInItem",
    "StkOpening",
    "StkOpeningItem",
    "StkStock",
    "StkStockLog",
    "SysBackupLog",
    "SysConfig",
    "SysFile",
    "SysModule",
    "SysModuleMigration",
    "SysNotification",
    "SysNotificationDelivery",
    "SysOperationLog",
    "SysPermission",
    "SysRole",
    "SysRolePermission",
    "SysSession",
    "SysStorage",
    "SysUser",
]
